### ISSUE TITLE
基于GoFrame、Layui、Vue等技术栈的敏捷后台开发框架

### ISSUE THREAD

**Issue by easygoadmin** [gogf/awesome-gf#10]
投递软件名称：EasyGoAdmin - 基于GoFrame、Layui、Vue等技术栈的敏捷后台开发框架；
投建软件仓库：
1、Layui版本：https://gitee.com/easygoadmin/EasyGoAdmin_GoFrame_Layui
2、Vue2.x+ElementUI版本：https://gitee.com/easygoadmin/EasyGoAdmin_GoFrame_EleVue
3、Vue3.x+AntDesign版本：https://gitee.com/easygoadmin/EasyGoAdmin_GoFrame_AntdVue
投递软件官网：https://www.easygoadmin.vip

**Comment by houseme** [comment]
建议直接pr,更新`readme.md`  ，谢谢 @easygoadmin
